; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
test_framework = googletest
test_speed = 115200
monitor_speed = 115200
build_flags = 
	-Iinclude -DDEBUG_ESP_HTTP_CLIENT -DDEBUG_ESP_PORT=Serial -DCORE_DEBUG_LEVEL=4 -DTTGO_BOARD_VERSION=1
lib_deps = 
	google/googletest@^1.12.1
	bblanchon/ArduinoJson@^6.21.3
    zinggjm/GxEPD2@^1.5.2
    https://github.com/me-no-dev/ESPAsyncWebServer.git ; solves bug in official repo
    ayushsharma82/AsyncElegantOTA@^2.2.8

; gtest is using a lot of space for test build - will need to see how much space the web server 
; needs on spiffs for config - should be small so this should be ok
board_build.partitions = min_spiffs.csv ; 1.9MB app w/ OTA, 190KB spiffs
